version: '3.8'

services:
  sentiment_analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - FLUTTER_FLAVOR=prod
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY}
    volumes:
      - ./build:/app/build
    restart: unless-stopped
